-- MySQL Script generated by MySQL Workbench
-- 01/28/20 15:11:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Data for table `skoule`.`teacher`
-- -----------------------------------------------------
START TRANSACTION;
USE `skoule`;
INSERT INTO `skoule`.`teacher` (`id`, `firstname`, `lastname`, `job`, `status`, `created_at`, `updated_at`) VALUES (1, 'Baptiste', 'Delphin', 'Formateur PHP/MySQL', 1, DEFAULT, NULL);
INSERT INTO `skoule`.`teacher` (`id`, `firstname`, `lastname`, `job`, `status`, `created_at`, `updated_at`) VALUES (2, 'Stéphane', 'Pellier', 'Formateur PHP/MySQL', 1, DEFAULT, NULL);
INSERT INTO `skoule`.`teacher` (`id`, `firstname`, `lastname`, `job`, `status`, `created_at`, `updated_at`) VALUES (3, 'Pauline', 'Grange', 'Formateur PHP/MySQL', 1, DEFAULT, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `skoule`.`student`
-- -----------------------------------------------------
START TRANSACTION;
USE `skoule`;
INSERT INTO `skoule`.`student` (`id`, `firstname`, `lastname`, `status`, `created_at`, `updated_at`, `teacher_id`) VALUES (1, 'Théo', 'Beaudouin', 1, DEFAULT, NULL, 2);
INSERT INTO `skoule`.`student` (`id`, `firstname`, `lastname`, `status`, `created_at`, `updated_at`, `teacher_id`) VALUES (2, 'Caroline', 'Flament', 1, DEFAULT, NULL, 1);
INSERT INTO `skoule`.`student` (`id`, `firstname`, `lastname`, `status`, `created_at`, `updated_at`, `teacher_id`) VALUES (3, 'Mathieu', 'Pajot', 1, DEFAULT, NULL, 1);
INSERT INTO `skoule`.`student` (`id`, `firstname`, `lastname`, `status`, `created_at`, `updated_at`, `teacher_id`) VALUES (4, 'Martin', 'Ferret', 1, DEFAULT, NULL, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `skoule`.`app_user`
-- -----------------------------------------------------
START TRANSACTION;
USE `skoule`;
INSERT INTO `skoule`.`app_user` (`id`, `email`, `name`, `password`, `role`, `status`, `created_at`, `updated_at`) VALUES (1, 'lucie@skoule.fr', 'Lucie Copin', '$2y$10$EePMx53146HlfIrHN7Ooree78V5nlLrhNCM.dZ9wL8NbQXRJbWp1O', 'admin', 1, DEFAULT, NULL);
INSERT INTO `skoule`.`app_user` (`id`, `email`, `name`, `password`, `role`, `status`, `created_at`, `updated_at`) VALUES (2, 'benji@skoule.fr', 'Benjamin Gahéry', '$2y$10$CbxKjJ7khu/xmSlRCtDgSeChpi.2R83IjEvpFHTA1FhQ1ATY.4way', 'user', 1, DEFAULT, NULL);

COMMIT;
